name: Collect and Deduplicate Trackers

on:
  schedule:
    - cron: "0 * * * *" # 每小时执行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run fetch_and_dedup.py
        run: python fetch_and_dedup.py

      - name: Commit and push changes
        run: |
          git config --global user.name "vampireisoves"
          git config --global user.email "893751627@qq.com"
          git add out.txt
          git commit -m "Update out.txt by GitHub Actions" || echo "No changes to commit"
          git push
